os: linux
dist: xenial
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-pip python-dev build-essential
  - sudo pip3 install --upgrade pip
  - sudo pip3 install meson
  - sudo pip3 install ninja

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - chmod +x
  - sudo ./appimage-build.sh

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Bottles*.AppImage*
