env:
  global:
  - PACKAGE_NAME=bottles
  - UPLOADTOOL_SUFFIX=v1

before_install:
  - sudo apt-get install fakeroot
  - export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
  - export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb

script:
  - dpkg-buildpackage -rfakeroot -b -uc -us
  - ls
  - mv ../*.deb $PACKAGE_NAME_VERSION

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.deb
