env:
  global:
  - PACKAGE_NAME=bottles

before_install:
- export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb

script:
- ls
- dpkg-deb --build ../Bottles
- mv *.deb PACKAGE_NAME_VERSION.deb

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.deb