name: bottles
version: git
summary: Bottles
description: "Easily run Windows software on Linux with 🍷 Bottles!"

base: core20
confinement: devmode
grade: devel

architectures:
  - build-on: amd64

plugs:
  gnome-3-32-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-38-2020

parts:
  bottles:
    plugin: meson
    build-packages:
      - python3
      - python3-distutils
      - gettext
      - libglib2.0-dev
      - appstream-util
      - desktop-file-utils
      - gsettings-desktop-schemas-dev
    source: . # https://github.com/bottlesdevs/Bottles.git
    stage-packages:
      - python3-gi
      - gir1.2-gtk-3.0
      - libnotify4
      - libnotify-dev
      - libgtk-3-dev

apps:
  bottles:
    command: bottles
    plugs:
      - desktop
      - unity7
      - gsettings
      - x11
      - home
      - network
      - removable-media
      - opengl
    slots:
      - dbus-bottles
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages:$SNAP/usr/share/bottles
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GTK_USE_PORTAL: "1"
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: com.usebottles.bottles
