name: bottles
version: git
summary: Bottles
description: |
  Easily run Windows software on Linux with 🍷 Bottles!
base: core18
confinement: strict

parts:
  bottles:
    plugin: meson
    build-packages:
      - gettext
      - libgtk-3-dev
      - libglib2.0-dev
      - python3-setuptools
      - gsettings-desktop-schemas-dev
      - appstream
      - appstream-util
      - desktop-file-utils
    stage-packages:
      - python3
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - gir1.2-gtk-3.0
    source: https://github.com/bottlesdevs/Bottles.git

apps:
  bottles:
    command: bin/bottles
    plugs:
      - desktop
      - gsettings
      - wayland
      - x11
      - home
      - network
    slots:
      - dbus-bottles

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: com.usebottles.bottles
