name: bottles
version: git
summary: Bottles
description: "Easily run Windows software on Linux with 🍷 Bottles!"
license: GPL-3.0+

base: core20
confinement: strict
grade: devel

parts:

  bottles:
    plugin: meson
    meson-parameters: [--prefix=/snap/bottles/current/usr]
    source: . # https://github.com/bottlesdevs/Bottles.git
    override-pull: |
      snapcraftctl pull
      sed -i -e 's|@PYTHON@|/usr/bin/python3|g' src/bottles.in
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    build-packages:
      - python3
      - python3-distutils
      - gettext
      - libglib2.0-dev
      - appstream-util
      - desktop-file-utils
      - gsettings-desktop-schemas-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libnotify4
      - libnotify-dev
      - libgtk-3-dev

apps:
  bottles:
    command: bin/desktop-launch $SNAP/usr/local/bin/bottles
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - home
      - gsettings
      - unity7
      - x11
      - network
      - audio-playback
      - removable-media
    slots:
      - dbus-bottles

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: com.usebottles.bottles
