name: bottles
version: git
summary: Bottles
description: |
  Easily run Windows software on Linux with 🍷 Bottles!
base: core18
confinement: classic

parts:
  bottles:
    plugin: meson
    build-packages: [python3, python3-setuptools, gettext, libgtk-3-dev, gsettings-desktop-schemas-dev, appstream, desktop-file-utils]
    stage-packages: [python3, python3-gi]
    source: .

apps:
  bottles:
    command: bin/bottles
