name: bottles
version: git
summary: Bottles
description: "Easily run Windows software on Linux with 🍷 Bottles!"

base: core18
confinement: strict
grade: devel

parts:
  bottles:
    plugin: meson
    build-packages:
      - python3
      - python3-distutils
      - gettext
      - libglib2.0-dev
      - appstream-util
      - desktop-file-utils
      - gsettings-desktop-schemas-dev
    source: . # https://github.com/bottlesdevs/Bottles.git
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libnotify4
      - libnotify-dev
      - libgtk-3-dev

apps:
  bottles:
    command: bin/bottles
    plugs:
      - desktop
      - desktop-legacy
      - home
      - gsettings
      - unity7
      - x11
      - network
    slots:
      - dbus-bottles
    environment:
      PYTHONPATH: $SNAP/gnome-platform/usr/lib/python3.6/site-packages
      LD_LIBRARY_PATH: $SNAP/gnome-platform/usr/lib:$LD_LIBRARY_PATH

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: com.usebottles.bottles
