name: bottles
version: git
summary: Bottles
description: "Easily run Windows software on Linux with 🍷 Bottles!"
license: GPL-3.0+

base: core18
confinement: strict
grade: devel

parts:
  bottles:
    plugin: meson
    build-packages:
      - python3
      - python3-distutils
      - gettext
      - libglib2.0-dev
      - appstream-util
      - desktop-file-utils
      - gsettings-desktop-schemas-dev
    source: . # https://github.com/bottlesdevs/Bottles.git
    override-pull: |
      snapcraftctl pull
      sed -i -e 's|@PYTHON@|/usr/bin/python3|g' src/bottles.in
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libnotify4
      - libnotify-dev
      - libgtk-3-dev

apps:
  bottles:
    command: bin/desktop-launch $SNAP/usr/local/bin/bottles
    extensions: [gnome-3-34]
    plugs:
      - desktop
      - desktop-legacy
      - home
      - gsettings
      - unity7
      - x11
      - network
      - audio-playback
      - removable-media
    slots:
      - dbus-bottles
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages:$SNAP/usr/share/bottles
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GTK_USE_PORTAL: "1"
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: com.usebottles.bottles
