name: bottles
version: git
summary: Bottles
description: |
  Easily run Windows software on Linux with 🍷 Bottles!
base: core18
confinement: classic

parts:
  bottles:
    plugin: meson
    build-packages:
	- python3
	- gettext
	- libgtk-3-dev
      	- python3
      	- python-gi-dev
    stage-packages:
    	- python3-gi
    source: .

apps:
  bottles:
    command: bin/bottles
