name: bottles
version: git
summary: Bottles
description: "Easily run Windows software on Linux with 🍷 Bottles!"
license: GPL-3.0+
icon: data/icons/hicolor/scalable/apps/com.usebottles.bottles.svg

base: core20
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, armhf]
    run-on: [amd64, armhf]
    
parts:

  bottles:
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    source: https://github.com/bottlesdevs/Bottles.git
    override-pull: |
      snapcraftctl pull
      sed -i -e 's|@PYTHON@|/usr/bin/python3|g' src/bottles.in
      sed -i.bak -e 's|Icon=com.usebottles.bottles|Icon=/usr/share/icons/hicolor/scalable/apps/com.usebottles.bottles.svg|g' data/com.usebottles.bottles.desktop.in
    build-packages:
      - python3
      - python3-distutils
      - gettext
      - libglib2.0-dev
      - appstream-util
      - desktop-file-utils
      - gsettings-desktop-schemas-dev
      - python3-pytoml
      - libnotify-dev
      - libgtk-3-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libnotify4
      - gamemode
      - libgamemode0

    organize:
      snap/bottles/current/usr: usr

apps:
  bottles:
    command: usr/bin/bottles
    desktop: usr/share/applications/com.usebottles.bottles.desktop
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - home
      - gsettings
      - unity7
      - x11
      - network
      - audio-playback
      - removable-media
    slots:
      - dbus-bottles

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: com.usebottles.bottles
