name: AppImage Unstable
on:
  push:
    branches: [ master ]
    tags:
      - 'test'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat VERSION)
        
      - name: Installing build dependencies
        run: |
          sudo apt install -y debhelper python3 python3.8-minimal python3-pip python3-setuptools gettext build-essential patchelf librsvg2-dev desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace ninja-build meson
      
      - name: appimagetool
        run: |
           sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
           sudo chmod +x /usr/local/bin/appimagetool
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install appimage-builder
        run: yes | sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git
      
      - name: Build AppImage
        run: appimage-builder --recipe AppImageBuilder.yml --skip-test

      - name: Build debian package
        run: |
          dpkg-buildpackage
        
      - name: Rename
        run: |
          mv Bottles-*-x86_64.AppImage Bottles-devel-x86_64.AppImage
          mv Bottles-*-x86_64.AppImage.zsync Bottles-devel-x86_64.AppImage.zsync

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: unstable
          title: Unstable build
          files: |
          	Bottles-*-x86_64.AppImage*
          	com.usebottles.bottles*.deb


