name: AppImage Release
on:
  push:
    branches: [ master ]
    tags:
      - 'test'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04 # Ubuntu Bionic Beaver
    steps:
      - name: Update Packages 
        run: |
          sudo apt update -qq
      - name: Install Packages 
        run: |
          sudo apt install python3-pip python-dev build-essential gettext git
          sudo pip3 install --upgrade pip
          sudo pip3 install meson
          sudo pip3 install ninja
      - name: Repo cloning
        run: git clone https://github.com/bottlesdevs/Bottles
      - name: g++ version check
        run: |
          if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
      - name: Executing Script
        run: |
          cd Bottles
          chmod +x appimage-build.sh
          sudo ./appimage-build.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: true
          automatic_release_tag: continuous-unstable-gh
          title: Release build UNSTABLE (continuous)
          files: /home/runner/work/Bottles/Bottles/Bottles/build/Bottles-devel-x86_64.AppImage
