name: AppImage Release
on:
  push:
    branches: [ appimage-recipe ]
    tags:
      - 'test'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        with:
          recipe: AppImageBuilder.yml
