name: AppImage Release
on:
  push:
    branches: [ appimage-recipe ]
    tags:
      - 'test'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat VERSION)
        
      - name: Installing build dependencies
        run: |
          sudo apt install -y python3.8-minimal python3-pip python3-setuptools gettext build-essential patchelf librsvg2-dev desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace meson ninja-build
          
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        with:
          recipe: AppImageBuilder.yml
        
      - name: List files in directory
        run: ls
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage



